<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class HealthcheckResult
{
    /**
     * Date and time at which this check started in.
     *
     * @var \DateTime|null
     */
    protected $start;
    /**
     * Date and time at which this check ended in.
     *
     * @var string|null
     */
    protected $end;
    /**
     * ExitCode meanings:.

     *
     * @var int|null
     */
    protected $exitCode;
    /**
     * Output from last check.
     *
     * @var string|null
     */
    protected $output;

    /**
     * Date and time at which this check started in.
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Date and time at which this check started in.
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    public function setStart(?\DateTime $start): self
    {
        $this->start = $start;

        return $this;
    }

    /**
     * Date and time at which this check ended in.
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    public function getEnd(): ?string
    {
        return $this->end;
    }

    /**
     * Date and time at which this check ended in.
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    public function setEnd(?string $end): self
    {
        $this->end = $end;

        return $this;
    }

    /**
     * ExitCode meanings:.

    - other values: error running probe
     */
    public function getExitCode(): ?int
    {
        return $this->exitCode;
    }

    /**
     * ExitCode meanings:.

    - other values: error running probe
     */
    public function setExitCode(?int $exitCode): self
    {
        $this->exitCode = $exitCode;

        return $this;
    }

    /**
     * Output from last check.
     */
    public function getOutput(): ?string
    {
        return $this->output;
    }

    /**
     * Output from last check.
     */
    public function setOutput(?string $output): self
    {
        $this->output = $output;

        return $this;
    }
}
