<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class SwarmInitPostBody
{
    /**
     * Listen address used for inter-manager communication, as well.
     *
     * @var string|null
     */
    protected $listenAddr;
    /**
     * Externally reachable address advertised to other nodes. This.
     *
     * @var string|null
     */
    protected $advertiseAddr;
    /**
     * Address or interface to use for data path traffic (format:.
     *
     * @var string|null
     */
    protected $dataPathAddr;
    /**
     * DataPathPort specifies the data path port number for data traffic.
     *
     * @var int|null
     */
    protected $dataPathPort;
    /**
     * Default Address Pool specifies default subnet pools for global.
     *
     * @var string[]|null
     */
    protected $defaultAddrPool;
    /**
     * Force creation of a new swarm.
     *
     * @var bool|null
     */
    protected $forceNewCluster;
    /**
     * SubnetSize specifies the subnet size of the networks created.
     *
     * @var int|null
     */
    protected $subnetSize;
    /**
     * User modifiable swarm configuration.
     *
     * @var SwarmSpec|null
     */
    protected $spec;

    /**
     * Listen address used for inter-manager communication, as well.
    is omitted, the default swarm listening port is used.
     */
    public function getListenAddr(): ?string
    {
        return $this->listenAddr;
    }

    /**
     * Listen address used for inter-manager communication, as well.
    is omitted, the default swarm listening port is used.
     */
    public function setListenAddr(?string $listenAddr): self
    {
        $this->listenAddr = $listenAddr;

        return $this;
    }

    /**
     * Externally reachable address advertised to other nodes. This.
    not specified, it will be automatically detected when possible.
     */
    public function getAdvertiseAddr(): ?string
    {
        return $this->advertiseAddr;
    }

    /**
     * Externally reachable address advertised to other nodes. This.
    not specified, it will be automatically detected when possible.
     */
    public function setAdvertiseAddr(?string $advertiseAddr): self
    {
        $this->advertiseAddr = $advertiseAddr;

        return $this;
    }

    /**
     * Address or interface to use for data path traffic (format:.
    management traffic of the cluster.
     */
    public function getDataPathAddr(): ?string
    {
        return $this->dataPathAddr;
    }

    /**
     * Address or interface to use for data path traffic (format:.
    management traffic of the cluster.
     */
    public function setDataPathAddr(?string $dataPathAddr): self
    {
        $this->dataPathAddr = $dataPathAddr;

        return $this;
    }

    /**
     * DataPathPort specifies the data path port number for data traffic.
    if no port is set or is set to 0, default port 4789 will be used.
     */
    public function getDataPathPort(): ?int
    {
        return $this->dataPathPort;
    }

    /**
     * DataPathPort specifies the data path port number for data traffic.
    if no port is set or is set to 0, default port 4789 will be used.
     */
    public function setDataPathPort(?int $dataPathPort): self
    {
        $this->dataPathPort = $dataPathPort;

        return $this;
    }

    /**
     * Default Address Pool specifies default subnet pools for global.
     *
     * @return string[]|null
     */
    public function getDefaultAddrPool(): ?array
    {
        return $this->defaultAddrPool;
    }

    /**
     * Default Address Pool specifies default subnet pools for global.
     *
     * @param string[]|null $defaultAddrPool
     */
    public function setDefaultAddrPool(?array $defaultAddrPool): self
    {
        $this->defaultAddrPool = $defaultAddrPool;

        return $this;
    }

    /**
     * Force creation of a new swarm.
     */
    public function getForceNewCluster(): ?bool
    {
        return $this->forceNewCluster;
    }

    /**
     * Force creation of a new swarm.
     */
    public function setForceNewCluster(?bool $forceNewCluster): self
    {
        $this->forceNewCluster = $forceNewCluster;

        return $this;
    }

    /**
     * SubnetSize specifies the subnet size of the networks created.
    from the default subnet pool.
     */
    public function getSubnetSize(): ?int
    {
        return $this->subnetSize;
    }

    /**
     * SubnetSize specifies the subnet size of the networks created.
    from the default subnet pool.
     */
    public function setSubnetSize(?int $subnetSize): self
    {
        $this->subnetSize = $subnetSize;

        return $this;
    }

    /**
     * User modifiable swarm configuration.
     */
    public function getSpec(): ?SwarmSpec
    {
        return $this->spec;
    }

    /**
     * User modifiable swarm configuration.
     */
    public function setSpec(?SwarmSpec $spec): self
    {
        $this->spec = $spec;

        return $this;
    }
}
