<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class TaskSpecResources
{
    /**
     * An object describing the resources which can be advertised by a node and.
     *
     * @var ResourceObject|null
     */
    protected $limits;
    /**
     * An object describing the resources which can be advertised by a node and.
     *
     * @var ResourceObject|null
     */
    protected $reservation;

    /**
     * An object describing the resources which can be advertised by a node and.
    requested by a task.
     */
    public function getLimits(): ?ResourceObject
    {
        return $this->limits;
    }

    /**
     * An object describing the resources which can be advertised by a node and.
    requested by a task.
     */
    public function setLimits(?ResourceObject $limits): self
    {
        $this->limits = $limits;

        return $this;
    }

    /**
     * An object describing the resources which can be advertised by a node and.
    requested by a task.
     */
    public function getReservation(): ?ResourceObject
    {
        return $this->reservation;
    }

    /**
     * An object describing the resources which can be advertised by a node and.
    requested by a task.
     */
    public function setReservation(?ResourceObject $reservation): self
    {
        $this->reservation = $reservation;

        return $this;
    }
}
